/// <reference types="@sveltejs/kit" />
/// <reference lib="webworker" />

import { build, files, version } from "$service-worker";

declare const self: ServiceWorkerGlobalScope;

const CACHE_NAME = `hager-scanner-${version}`;

// Everything needed for offline mode
const ASSETS = [
  ...build, // hashed JS/CSS generated by vite
  ...files, // static folder
  "/", // root document
  "/scan", // your QR scanner page
];

// Install SW → cache all assets
self.addEventListener("install", (event: any) => {
  console.log("[SW] Installing…");

  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log("[SW] Caching assets:", ASSETS);
      return cache.addAll(ASSETS);
    }),
  );

  self.skipWaiting();
});

// Activate SW → cleanup old caches
self.addEventListener("activate", (event: any) => {
  console.log("[SW] Activating…");

  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.map((key) => {
          if (key !== CACHE_NAME) {
            console.log("[SW] Deleting old cache:", key);
            return caches.delete(key);
          }
        }),
      ),
    ),
  );

  self.clients.claim();
});

// Fetch handler → Network first, fallback to cache
self.addEventListener("fetch", (event: any) => {
  const request = event.request;
  const url = new URL(request.url);

  // Don't cache API requests - let them fail naturally so the app can handle errors
  if (url.pathname.startsWith("/api/")) {
    event.respondWith(fetch(request));
    return;
  }

  // For all other requests: Network first, fallback to cache
  event.respondWith(
    fetch(request).catch(() => {
      return caches.match(request).then((cached) => {
        if (cached) return cached;

        // If no exact match, fall back to root
        if (request.mode === "navigate") {
          return caches.match("/");
        }

        return undefined;
      });
    }),
  );
});
